config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:destroy]
  end

  resources :charges, only: [:new, :create, :destroy]

  devise_for :users

  root "welcome#index"

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborations
  has_many :private_wikis, through: :collaborations, source: :wiki
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  def public?
    self.private == false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized for that! So stop it."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken],
      plan: "premium"
    )

    Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium Lorbo - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attributes(
      stripe_id: customer.id,
      role: :premium,
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! You are now a Premium Lorbo."
    redirect_to edit_user_registration_path

  rescue Stripe::CardError => elephant
    flash.now[:alert] = elephant.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Lorbo - #{current_user.email}",
      amount: Amount.default
    }
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    # To do - make sure we have a subscription before accessing id
    subscription_id = customer.subscriptions.data.first.id
    customer.subscriptions.retrieve(subscription_id).delete

    # must switch all wikis from private to public
    current_user.wikis.update_all(private: false)
    current_user.update_attributes(role: :standard)

    flash[:notice] = "Your account has been successfully downgraded."
    redirect_to edit_user_registration_path

  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def destroy
    @user = User.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])

    @collaboration = Collaboration.where(user_id: params[:id], wiki_id: params[:wiki_id]).first
    
    authorize @collaboration

    if @collaboration.destroy # or @wiki.collaborators.delete(@user)
      flash[:notice] = "\"#{@user.email}\" was deleted successfully."
      redirect_to wiki_path(@wiki)
    else
      flash.now[:alert] = "There was an error removing the collaborator."
      render :show
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :authenticate_user!, except: [:index] 

  def index
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

    authorize @wiki

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)

    # TODO - investigate how to call html_safe from controller
    @wiki.title = markdown.render(@wiki.title)
    @wiki.body = markdown.render(@wiki.body)
  end

  def new
    @wiki = Wiki.new

    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if params[:wiki][:private]
      @wiki.private = params[:wiki][:private]
    end

    unless current_user.nil?
      @wiki.user_id = current_user.id
    end

    add_collaborators

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again later."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])

    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])

    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    add_collaborators

    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def add_collaborators
    if params[:collaborator_email] && params[:collaborator_email].present?
      user = User.where(email: params[:collaborator_email]).first
      if @wiki.collaborators.include?(user)
        flash[:alert] = "That user is already a collaborator."
      elsif user.nil?
        flash[:alert] = "This user does not exist."
      else
        @wiki.collaborators << user
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=devide-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Wikis", wikis_path %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to "Upgrade", new_charge_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <li class="navbar-text">Signed in as: <%= current_user.email %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <%= content_tag :div, msg, :class => "flash_#{name}" %>
          <% end %>
        <% end %>

      <%= yield %>

  </div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>Developed by Lorbo and Jean-Denis</p>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <div class="form-group">
    <%= label_tag(:collaborator_email, "Collaborators:") %>
    <%= text_field_tag :collaborator_email, nil, placeholder: "lorbo@lorbosdomain.com" %>
  </div>

  <ul>
    <% @wiki.collaborators.each do |collaborator| %>
    <li>

      <%= collaborator.email %>
      <%= link_to "Remove", wiki_collaborator_path(@wiki, collaborator), method: :delete, class: "btn btn-danger", confirm: "Are you sure you want to remove this collaborator?" %> 

    </li>
  <% end %>
  </ul>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>

<% @wikis.each do |wiki| %>

<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki %>
    </h4>
  </div>
</div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <div class="form-group">
    <%= label_tag(:collaborator_email, "Collaborators:") %>
    <%= text_field_tag :collaborator_email, nil, placeholder: "lorbo@lorbosdomain.com" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>

<% end %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title.html_safe %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @wiki.body.html_safe %></p>
    <ul>
      <% @wiki.collaborators.each do |collaborator| %>
      <li><%= collaborator.email %></li>
    <% end %>
    </ul>
  </div>
  <div class="col-md-4">
  <% if policy(@wiki).update? %>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% end %>
  <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  <% end %>
  </div>
</div>